logging.config=classpath:logback-base.xml

pn.env.runtime=PROD
spring.application.name=pn-workflow-manager

management.endpoints.web.exposure.include=health,metrics,loggers

# Queue inbound event configuration
pn.workflow-manager.topics.safe-storage-events=pn-safestore_to_workflowmanager
