logging.config=classpath:logback-base.xml

pn.env.runtime=PROD
spring.application.name=pn-workflow-manager

management.endpoints.web.exposure.include=health,metrics,loggers

pn.workflow-manager.paper-channel.sender-address.fullname=PagoPA S.p.A.
pn.workflow-manager.paper-channel.sender-address.address=Via Sardegna n. 38
pn.workflow-manager.paper-channel.sender-address.zipcode=00187
pn.workflow-manager.paper-channel.sender-address.city=Roma
pn.workflow-manager.paper-channel.sender-address.pr=Roma
pn.workflow-manager.paper-channel.sender-address.country=Italia

# Campaign configuration
campaign.table-name=${PN_WORKFLOWMANAGER_CAMPAIGNS_TABLE_NAME:Campaigns}
pn.workflow-manager.cx-id=5b994d4a-0fa8-47ac-9c7b-354f1d44a1ce