logging.config=classpath:logback-base.xml

pn.env.runtime=PROD
spring.application.name=pn-workflow-manager

management.endpoints.web.exposure.include=health,metrics,loggers

# Queue inbound event configuration
pn.workflow-manager.topics.safe-storage-events=pn-safestore_to_workflowmanager

pn.workflow-manager.paper-channel.sender-address.fullname=PagoPA S.p.A.
pn.workflow-manager.paper-channel.sender-address.address=Via Sardegna n. 38
pn.workflow-manager.paper-channel.sender-address.zipcode=00187
pn.workflow-manager.paper-channel.sender-address.city=Roma
pn.workflow-manager.paper-channel.sender-address.pr=Roma
pn.workflow-manager.paper-channel.sender-address.country=Italia