AWSTemplateFormatVersion: '2010-09-09'
Description: Data quality template, creates a nested stack for the campaign statistics Glue Table and Crawler

Parameters:
  TemplateBucketBaseUrl:
    Type: String
    Description: The S3 bucket from which to fetch the templates used by this stack.

  GlueServiceRoleArn:
    Type: String
    Description: Service role for the Glue Crawler.

  LogsBucketName:
    Type: String
    Description: Logs bucket name

  GlueDatabaseName:
    Type: String
    Description: Name of the Glue Database

  CampaignStatisticsTableName:
    Type: String
    Description: |
      DynamoDB table name for campaign statistics, also used to identify the S3
      directory where related CDC files are stored. Supply this value from the
      CampaignStatisticsTableName output of the storage stack.

  CampaignStatisticsGlueTableName:
    Type: String
    AllowedPattern: '^[a-z_]+$'
    ConstraintDescription: |
      Glue table name for campaign statistics, accepts only lowercase letters and underscores.
    Default: pn_campaign_statistics

  CampaignsTableName:
    Type: String
    Description: |
      DynamoDB table name for campaigns, also used to identify the S3
      directory where related CDC files are stored. Supply this value from the
      CampaignsTableName output of the storage stack.

  CampaignsGlueTableName:
    Type: String
    AllowedPattern: '^[a-z_]+$'
    ConstraintDescription: |
      Glue table name for campaigns, accepts only lowercase letters and underscores.
    Default: pn_campaigns

Resources:
  PnCampaignStatisticsDataQualityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/cdc-glue.yaml
      Parameters:
        DynamoTableName: !Ref CampaignStatisticsTableName
        GlueTableName: !Ref CampaignStatisticsGlueTableName
        GlueServiceRoleArn: !Ref GlueServiceRoleArn
        LogsBucketName: !Ref LogsBucketName
        GlueDatabaseName: !Ref GlueDatabaseName
        # Mapping Logico:
        # pk = senderId
        # sk = campaignId
        DynamoDBKeysStructure: |
          struct<senderId:struct<S:string>,campaignId:struct<S:string>>
        DynamoDBNewImageStructure: |
          struct<
            senderId:struct<S:string>,
            campaignId:struct<S:string>,
            totalSent:struct<NULL:boolean,N:string>,
            totalAccepted:struct<NULL:boolean,N:string>,
            totalRefused:struct<NULL:boolean,N:string>,
            totalViewed:struct<NULL:boolean,N:string>,
            totalUndeliverable:struct<NULL:boolean,N:string>,
            totalDelivered:struct<NULL:boolean,N:string>,
            workflowDone:struct<NULL:boolean,N:string>,
            digitalSentIO:struct<NULL:boolean,N:string>,
            digitalSentEMAIL:struct<NULL:boolean,N:string>,
            digitalSentPEC:struct<NULL:boolean,N:string>,
            digitalSentSMS:struct<NULL:boolean,N:string>,
            analogSentRS:struct<NULL:boolean,N:string>,
            receivedIO:struct<NULL:boolean,N:string>,
            receivedEMAIL:struct<NULL:boolean,N:string>,
            receivedPEC:struct<NULL:boolean,N:string>,
            receivedRS:struct<NULL:boolean,N:string>,
            viewedIO:struct<NULL:boolean,N:string>,
            firstViewedCount:struct<NULL:boolean,N:string>,
            viewedSEND:struct<NULL:boolean,N:string>,
            paid:struct<NULL:boolean,N:string>,
            lastCompletedTimestamp:struct<NULL:boolean,S:string>
          >

  PnCampaignsDataQualityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/cdc-glue.yaml
      Parameters:
        DynamoTableName: !Ref CampaignsTableName
        GlueTableName: !Ref CampaignsGlueTableName
        GlueServiceRoleArn: !Ref GlueServiceRoleArn
        LogsBucketName: !Ref LogsBucketName
        GlueDatabaseName: !Ref GlueDatabaseName
        # Mapping Logico:
        # pk = senderId
        # sk = campaignId
        DynamoDBKeysStructure: |
          struct<senderId:struct<S:string>,campaignId:struct<S:string>>
        DynamoDBNewImageStructure: |
          struct<
            campaignId:struct<S:string>,
            senderId:struct<S:string>,
            title:struct<S:string>,
            descriptionScope:struct<S:string>,
            startDate:struct<S:string>,
            endDate:struct<S:string>,
            status:struct<S:string>,
            senderContact:struct<S:string>,
            serviceName:struct<S:string>,
            serviceId:struct<S:string>,
            sensitiveContent:struct<BOOL:boolean>,
            stopOnViewed:struct<BOOL:boolean>,
            stopOnPayed:struct<BOOL:boolean>,
            workflow:struct<L:array<struct<M:struct<
              channel:struct<S:string>,
              desiredFeedback:struct<L:array<struct<S:string>>>,
              includeAttachment:struct<BOOL:boolean>,
              recipientType:struct<S:string>,
              timeout:struct<S:string>
            >>>>
          >