AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
    
  AlarmSNSTopicName:
    Type: String
    Description: ''

  #Log
  LogRetention:
    Type: Number
    Default: 14
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'
  
Resources:
  WorkflowManagerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-workflow-manager'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

  # Internal queues
  WorkflowManagerActionsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-workflow-manager_actions'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1

  #Log Group
  PnNotificationCostServiceLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-notification-cost-service'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

Outputs:
  # Scheduled Actions
  WorkflowManagerActionsQueueName:
    Value: !GetAtt WorkflowManagerActionsQueue.Outputs.QueueName
    Description: pn-workflow-manager actions queue name
  WorkflowManagerActionsQueueURL:
    Value: !GetAtt WorkflowManagerActionsQueue.Outputs.QueueURL
    Description: pn-workflow-manager actions queue URL
  WorkflowManagerActionsQueueARN:
    Value: !GetAtt WorkflowManagerActionsQueue.Outputs.QueueARN
    Description: pn-workflow-manager actions queue ARN
  WorkflowManagerActionsQueueAlarmARN:
    Value: !GetAtt WorkflowManagerActionsQueue.Outputs.SqsDLQAlarmArn
    Description: pn-workflow-manager actions queue dlq alarm queue
  WorkflowManagerActionsQueueAgeAlarmARN:
    Value: !GetAtt WorkflowManagerActionsQueue.Outputs.SqsAgeAlarmArn
    Description: pn-workflow-manager actions queue age alarm ARN
  # Log groups
  EcsWorkflowLogGroup:
    Value: !GetAtt WorkflowManagerLogGroup.Outputs.LogGroupName