package it.pagopa.pn.workflowmanager.exceptions;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;

public class WorkflowManagerExceptionCodes extends PnExceptionsCodes {
    public static final String ERROR_CODE_DELIVERYPUSH_ACTIONTYPENOTSUPPORTED = "PN_DELIVERYPUSH_ACTIONTYPENOTSUPPORTED";
    public static final String ERROR_CODE_DELIVERYPUSH_NOTIFICATIONFAILED = "PN_DELIVERYPUSH_NOTIFICATIONFAILED";
    public static final String ERROR_CODE_TIMELINESERVICE_TIMELINE_ELEMENT_NOT_PRESENT = "PN_TIMELINESERVICE_TIMELINEELEMENTNOTPRESENT";
    public static final String ERROR_CODE_DELIVERY_CAMPAIGN_NOT_FOUND = "PN_DELIVERY_CAMPAIGN_NOT_FOUND";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_INVALID_SUPPORTED_EVENT = "PN_WORKFLOWMANAGER_ROUTER_INVALID_SUPPORTED_EVENT";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_MULTIPLE_HANDLERS_FOUND = "PN_WORKFLOWMANAGER_ROUTER_MULTIPLE_HANDLERS_FOUND";
    public static final String ERROR_CODE_WORFKLOWMANAGER_ROUTER_DESERIALIZATION = "PN_WORKFLOWMANAGER_ROUTER_DESERIALIZATION";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_EVENT_TYPE_MISSING = "PN_WORKFLOWMANAGER_ROUTER_EVENT_TYPE_MISSING";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_HANDLER_NOT_FOUND = "PN_WORKFLOWMANAGER_ROUTER_NOT_FOUND";
    public static final String ERROR_CODE_WORKFLOWMANAGER_HANDLEEVENTFAILED = "PN_WORKFLOWMANAGER_HANDLEEVENTFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_ACTION_CONFLICT = "PN_ACTIONMANAGER_ERROR_CODE_ACTION_CONFLICT";
}
