package it.pagopa.pn.workflowmanager.exceptions;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;

public class WorkflowManagerExceptionCodes extends PnExceptionsCodes {
    public static final String ERROR_CODE_DELIVERYPUSH_ACTIONTYPENOTSUPPORTED = "PN_DELIVERYPUSH_ACTIONTYPENOTSUPPORTED";
    public static final String ERROR_CODE_DELIVERYPUSH_NOTIFICATIONFAILED = "PN_DELIVERYPUSH_NOTIFICATIONFAILED";
    public static final String ERROR_CODE_TIMELINESERVICE_TIMELINE_ELEMENT_NOT_PRESENT = "PN_TIMELINESERVICE_TIMELINEELEMENTNOTPRESENT";
    public static final String ERROR_CODE_DELIVERY_CAMPAIGN_NOT_FOUND = "PN_DELIVERY_CAMPAIGN_NOT_FOUND";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_INVALID_SUPPORTED_EVENT = "PN_WORKFLOWMANAGER_ROUTER_INVALID_SUPPORTED_EVENT";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_MULTIPLE_HANDLERS_FOUND = "PN_WORKFLOWMANAGER_ROUTER_MULTIPLE_HANDLERS_FOUND";
    public static final String ERROR_CODE_WORFKLOWMANAGER_ROUTER_DESERIALIZATION = "PN_WORKFLOWMANAGER_ROUTER_DESERIALIZATION";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_EVENT_TYPE_MISSING = "PN_WORKFLOWMANAGER_ROUTER_EVENT_TYPE_MISSING";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_HANDLER_NOT_FOUND = "PN_WORKFLOWMANAGER_ROUTER_NOT_FOUND";
    public static final String ERROR_CODE_WORKFLOWMANAGER_HANDLEEVENTFAILED = "PN_WORKFLOWMANAGER_HANDLEEVENTFAILED";
    public static final String ERROR_CODE_WORKFLOWMANAGER_SAVELEGALFACTSFAILED = "PN_WORKFLOWMANAGER_SAVELEGALFACTSFAILED";
    public static final String ERROR_CODE_WORKFLOWMANAGER_UPLOADFILEERROR = "PN_WORKFLOWMANAGER_UPLOADFILEERROR";
    public static final String ERROR_CODE_WORKFLOWMANAGER_PAPERCHANNELSENDCOSTCHANGED = "PN_WORKFLOWMANAGER_PAPERCHANNELSENDCOSTCHANGED";
    public static final String ERROR_CODE_WORKFLOWMANAGER_SENDPECNOTIFICATIONFAILED = "PN_WORKFLOWMANAGER_SENDPECNOTIFICATIONFAILED";
    public static final String ERROR_CODE_WORKFLOWMANAGER_CONFIGURATION_NOT_FOUND = "PN_WORKFLOWMANAGER_CONFIGURATIONNOTFOUND";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ACTION_CONFLICT = "PN_WORKFLOWMANAGER_ERROR_CODE_ACTION_CONFLICT";
    public static final String ERROR_CODE_WORKFLOWMANAGER_ROUTER_EVENT_TYPE_NOT_SUPPORTED = "PN_WORKFLOWMANAGER_ROUTER_EVENT_TYPE_NOT_SUPPORTED";

    public static final String ERROR_CODE_WORKFLOWMANAGER_INVALID_CAMPAIGN_STATUS = "PN_WORKFLOWMANAGER_ERROR_CODE_INVALID_CAMPAIGN_STATUS";
    public static final String ERROR_CODE_WORKFLOWMANAGER_GENERIC_WORKFLOW_ERROR = "PN_WORKFLOWMANAGER_GENERICWORKFLOWERROR";
    public static final String ERROR_CODE_WORKFLOWMANAGER_SEND_ON_CHANNEL_ERROR = "PN_WORKFLOWMANAGER_SENDONCHANNELERROR";
    public static final String ERROR_CODE_WORKFLOWMANAGER_UNKNOWN_EVENT_CODE = "PN_WORKFLOWMANAGER_UNKNOWNEVENTCODE";
    public static final String ERROR_CODE_WORKFLOWMANAGER_CHANNEL_TRIGGER_EVENT_NOT_FOUND = "PN_WORKFLOWMANAGER_CHANNELTRIGGEREVENTNOTFOUND";
    public static final String ERROR_CODE_WORKFLOWMANAGER_PAYMENT_NOT_FOUND = "PN_WORKFLOWMANAGER_PAYMENTNOTFOUND";
    public static final String ERROR_CODE_WORKFLOWMANAGER_SENDSMSNOTIFICATIONFAILED = "PN_WORKFLOWMANAGER_SENDSMSNOTIFICATIONFAILED";
    public static final String ERROR_CODE_WORKFLOWMANAGER_SENDEMAILNOTIFICATIONFAILED = "PN_WORKFLOWMANAGER_SENDEMAILNOTIFICATIONFAILED";
    public static final String ERROR_CODE_WORKFLOWMANAGER_UNSUPPORTED_DOCUMENT_CREATION_TYPE = "PN_WORKFLOWMANAGER_UNSUPPORTED_DOCUMENT_CREATION_TYPE";
    public static final String ERROR_CODE_WORKFLOWMANAGER_INVALID_EVENT_RECEIVED = "PN_WORKFLOWMANAGER_INVALIDEVENTRECEIVED";
    public static final String ERROR_CODE_WORKFLOWMANAGER_PAPERUPDATEFAILED = "PN_WORKFLOWMANAGER_PAPERUPDATEFAILED";
}
