logging.config=config/logback-local.xml
server.port=8095

# Runtime mode
pn.env.runtime=DEVELOPMENT

spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

# Queue inbound event configuration
pn.workflow-manager.topics.action-queue=pn-workflow-manager_action
pn.workflow-manager.topics.digital-queue=pn-workflow-manager_digital_event
pn.workflow-manager.topics.analog-queue=pn-workflow-manager_analog_event
pn.workflow-manager.topics.io-queue=pn-workflow-manager_io_event
pn.workflow-manager.topics.informal-queue=pn-workflow_manager_inputs
pn.workflow-manager.topics.safe-storage-events=pn-safestore_to_workflowmanager

#external client
pn.workflow-manager.delivery-base-url=http://localhost:8090
pn.workflow-manager.timeline-client-base-url=http://localhost:8093
pn.workflow-manager.external-channels-base-url=http://localhost:8096
pn.workflow-manager.action-manager-base-url=http://localhost:8092
pn.workflow-manager.template-engine-base-url=http://localhost:8095
pn.workflow-manager.io-connector-base-url=http://localhost:8094
pn.workflow-manager.safe-storage-base-url=http://localhost:8094

pn.workflow-manager.pn-send-mode=1970-01-01T00:00:00Z;DOCUMENTS;DOCUMENTS|PAYMENTS;COVERPAGE|DOCUMENTS|PAYMENTS

pn.workflow-manager.io-polling-max-mins=5

pn.workflow-manager.search-digital-domicile-start-date=2026-09-01T00:00:00.000Z