logging.config=config/logback-local.xml
server.port=8095

# Runtime mode
pn.env.runtime=DEVELOPMENT

spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

# Queue inbound event configuration
pn.workflow-manager.topics.action-queue=pn-workflow-manager-action-queue
pn.workflow-manager.topics.digital-queue=pn-workflow-manager-digital-event-queue
pn.workflow-manager.topics.analog-queue=pn-workflow-manager-analog-event-queue
pn.workflow-manager.topics.io-queue=pn-workflow-manager-io-event-queue